#!/usr/bin/env bash
# Asterisk VoIP PBX installer for Raspberry Pi 3B (Debian 12 "bookworm").
# Usage: sudo ./install.sh            (reads optional voip.conf next to this script)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ -f "$SCRIPT_DIR/voip.conf" ]] && source "$SCRIPT_DIR/voip.conf"

# ---- defaults (override in voip.conf) ----
EXTENSIONS="${EXTENSIONS:-1001 1002 1003}"   # space separated extension numbers
SIP_PORT="${SIP_PORT:-5060}"
RTP_START="${RTP_START:-10000}"
RTP_END="${RTP_END:-10100}"
ENABLE_FIREWALL="${ENABLE_FIREWALL:-yes}"    # configure ufw if yes
CREDS_FILE="/root/voip-credentials.txt"

log() { printf '\e[1;32m[+]\e[0m %s\n' "$*"; }
die() { printf '\e[1;31m[!]\e[0m %s\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Run as root: sudo $0"
grep -q 'VERSION_ID="12"' /etc/os-release || log "Warning: not Debian 12, continuing anyway"
for e in $EXTENSIONS; do [[ $e =~ ^[0-9]{3,6}$ ]] || die "Bad extension: $e"; done

log "Installing packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y asterisk asterisk-core-sounds-en-gsm asterisk-moh-opsound-gsm openssl
[[ "$ENABLE_FIREWALL" == yes ]] && apt-get install -y ufw

ASTDIR=/etc/asterisk
if [[ -d $ASTDIR && ! -f $ASTDIR/.pi-voip-backup-done ]]; then
  BK="/etc/asterisk.bak.$(date +%Y%m%d%H%M%S)"
  log "Backing up $ASTDIR to $BK"
  cp -a "$ASTDIR" "$BK"
  touch "$ASTDIR/.pi-voip-backup-done"
fi

# Keep existing passwords on re-run so phones don't break
declare -A PASS
if [[ -f $CREDS_FILE ]]; then
  while read -r ext pw; do [[ $ext =~ ^[0-9]+$ ]] && PASS[$ext]=$pw; done < <(grep -E '^[0-9]+ ' "$CREDS_FILE" || true)
fi
for e in $EXTENSIONS; do
  [[ -n "${PASS[$e]:-}" ]] || PASS[$e]="$(openssl rand -hex 10)"
done

log "Writing Asterisk configuration"
cat > $ASTDIR/pjsip.conf <<CONF
; Generated by pi-voip install.sh
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:${SIP_PORT}

CONF
for e in $EXTENSIONS; do
cat >> $ASTDIR/pjsip.conf <<CONF
[$e]
type=endpoint
context=internal
disallow=all
allow=ulaw,alaw,g722
auth=${e}-auth
aors=$e
callerid="Extension $e" <$e>
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
mailboxes=$e@default

[${e}-auth]
type=auth
auth_type=userpass
username=$e
password=${PASS[$e]}

[$e]
type=aor
max_contacts=3
remove_existing=yes
qualify_frequency=30

CONF
done

cat > $ASTDIR/extensions.conf <<CONF
; Generated by pi-voip install.sh
[general]
static=yes
writeprotect=no

[internal]
; Dial another extension (rings 25s, then voicemail)
exten => _XXXX.,1,NoOp(Call to \${EXTEN})
 same => n,Dial(PJSIP/\${EXTEN},25)
 same => n,Voicemail(\${EXTEN}@default,u)
 same => n,Hangup()
; *97 = check own voicemail
exten => *97,1,VoiceMailMain(\${CALLERID(num)}@default,s)
 same => n,Hangup()
; 600 = echo test
exten => 600,1,Answer()
 same => n,Playback(demo-echotest)
 same => n,Echo()
 same => n,Hangup()
CONF

cat > $ASTDIR/rtp.conf <<CONF
[general]
rtpstart=${RTP_START}
rtpend=${RTP_END}
CONF

{ echo "[general]"; echo "format=wav49|gsm|wav"; echo; echo "[default]"
  for e in $EXTENSIONS; do echo "$e => $((RANDOM % 9000 + 1000)),Extension $e,,,"; done
} > $ASTDIR/voicemail.conf
# Ensure no stale auth-less modules interfere: use PJSIP only
grep -q 'noload => chan_sip.so' $ASTDIR/modules.conf 2>/dev/null || \
  echo 'noload => chan_sip.so' >> $ASTDIR/modules.conf

chown -R asterisk:asterisk $ASTDIR
chmod 640 $ASTDIR/pjsip.conf $ASTDIR/voicemail.conf

if [[ "$ENABLE_FIREWALL" == yes ]]; then
  log "Configuring ufw (SSH, SIP, RTP)"
  ufw allow OpenSSH >/dev/null
  ufw allow "${SIP_PORT}/udp" >/dev/null
  ufw allow "${RTP_START}:${RTP_END}/udp" >/dev/null
  ufw --force enable >/dev/null
fi

log "Starting Asterisk"
systemctl enable asterisk
systemctl restart asterisk
sleep 3
systemctl is-active --quiet asterisk || die "Asterisk failed to start: journalctl -u asterisk"

IP="$(hostname -I | awk '{print $1}')"
{
  echo "# SIP server: $IP  port: $SIP_PORT  (UDP)"
  echo "# extension password"
  for e in $EXTENSIONS; do echo "$e ${PASS[$e]}"; done
} > "$CREDS_FILE"
chmod 600 "$CREDS_FILE"

log "Done. Server: $IP:$SIP_PORT"
log "Credentials saved to $CREDS_FILE (root only)"
log "Test: register a softphone, dial 600 (echo), or another extension. *97 = voicemail."
